Create or replace Table `speers-spielewiese-dev.jobs_ch.jobs_ch` AS
    SELECT
        name as storage_name,
        date as extraction_date,
        JSON_EXTRACT_SCALAR(json, '$.publication_end_date') AS publication_end_date,
        JSON_EXTRACT_SCALAR(json, '$._links.detail_de.href') AS detail_de_href,
        JSON_EXTRACT_SCALAR(json, '$._links.detail_fr.href') AS detail_fr_href,
        JSON_EXTRACT_SCALAR(json, '$._links.detail_en.href') AS detail_en_href,
        JSON_EXTRACT_SCALAR(json, '$.categories[0].lvl_0') AS category_lvl_0,
        JSON_EXTRACT_SCALAR(json, '$.categories[0].path') AS category_path,
        JSON_EXTRACT_SCALAR(json, '$.company_visible') AS company_visible,
        JSON_EXTRACT_SCALAR(json, '$.regions[0].lvl_0') AS region_lvl_0,
        JSON_EXTRACT_SCALAR(json, '$.regions[0].lvl_1') AS region_lvl_1,
        JSON_EXTRACT_SCALAR(json, '$.regions[0].lvl_2') AS region_lvl_2,
        JSON_EXTRACT_SCALAR(json, '$.regions[0].path') AS region_path,
        JSON_EXTRACT_SCALAR(json, '$.slug') AS slug,
        JSON_EXTRACT_SCALAR(json, '$.company_slug') AS company_slug,
        JSON_EXTRACT_SCALAR(json, '$.application_method') AS application_method,
        JSON_EXTRACT_SCALAR(json, '$.job_source_type') AS job_source_type,
        JSON_EXTRACT_SCALAR(json, '$.last_online_date') AS last_online_date,
        JSON_EXTRACT_SCALAR(json, '$.job_id') AS job_id,
        JSON_EXTRACT_SCALAR(json, '$.datapool_id') AS datapool_id,
        JSON_EXTRACT_SCALAR(json, '$.title') AS title,
        JSON_EXTRACT_SCALAR(json, '$.company_name') AS company_name,
        JSON_EXTRACT_SCALAR(json, '$.company_id') AS company_id,
        JSON_EXTRACT(json, '$._links') AS links_json,
        JSON_EXTRACT(json, '$.categories') AS categories_json,
        JSON_EXTRACT(json, '$.regions') AS regions_json,
        JSON_EXTRACT(json, '$.employment_position_ids') AS employment_position_ids_json,
        JSON_EXTRACT(json, '$.employment_grades') AS employment_grades_json,
        JSON_EXTRACT(json, '$.employment_type_ids') AS employment_type_ids_json,
        JSON_EXTRACT(json, '$.benefit_ids') AS benefit_ids_json,
        JSON_EXTRACT_SCALAR(json, '$.external_url') AS external_url,
        JSON_EXTRACT_SCALAR(json, '$.application_url') AS application_url,
        JSON_EXTRACT_SCALAR(json, '$.zipcode') AS zipcode,
        JSON_EXTRACT_SCALAR(json, '$.synonym') AS synonym,
        JSON_EXTRACT(json, '$.template') AS template_json,
        JSON_EXTRACT_SCALAR(json, '$.template_profession') AS template_profession,
        JSON_EXTRACT(json, '$.template_text') AS template_text_json,
        JSON_EXTRACT(json, '$.template_contact_address') AS template_contact_address_json,
        JSON_EXTRACT_SCALAR(json, '$.is_active') AS is_active,
        JSON_EXTRACT_SCALAR(json, '$.is_responsive') AS is_responsive,
        JSON_EXTRACT_SCALAR(json, '$.is_paid') AS is_paid,
        JSON_EXTRACT_SCALAR(json, '$.headhunter_application_allowed') AS headhunter_application_allowed
    FROM `speers-spielewiese-dev.jobs_ch.jobs_ch_prep` ;